language: node_js
node_js:
- "6"
services:
  - postgresql: "9.6"
before_script:
  - psql -c "create database dms_test;" -U postgres
  - psql -c "CREATE USER Niccie;" -U postgres
  - sleep 3
script:
  - npm test
after_script:
  - npm run coverage
env:
  - SECRET_TOKEN_KEY=nottheactualthing NODE_ENV=test
