export const LOAD_DOCUMENTS_SUCCESS = 'LOAD_DOCUMENTS_SUCCESS';
export const LOAD_DOCUMENTBYID_SUCCESS = 'LOAD_DOCUMENTBYID_SUCCESS';
export const CREATE_USERS = 'CREATE_USERS';
export const LOG_USER = 'LOG_USER';
export const CREATED_DOCUMENT_SUCCESS = 'CREATED_DOCUMENT_SUCCESS';
export const UPDATED_DOCUMENT_SUCCESS = 'UPDATED_DOCUMENT_SUCCESS';
export const DELETED_DOCUMENT_SUCCESS = 'DELETED_DOCUMENT_SUCCESS';
export const LOADMY_DOCUMENTS_SUCCESS = 'LOADMY_DOCUMENTS_SUCCESS';
